spring:
  datasource:
    url: jdbc:sqlserver://sqlserver_anv:1533;databaseName=master
    username: sa
    password: Audrey123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  server:
    port: 8080
    ssl:
      enabled: false

mybatis:
  mapper-locations: classpath:/com/spr/infrastructure/mapper/*.xml
  type-aliases-package: com.spr.application.dto
